travis:
  secure:
    BINSTAR_TOKEN: dpxGCm6CeFpJhA1z5Vj8N08kMBpZUYLb2jmBBtzznoapC0jYcVjTIO3EqPIB1soIndMZT8GRTTJ/SDo5mEVtBxgIdshuvBuXKNRXK+ABKLsJ2uXPaIWpI6ORAU5AJjDhwWRyrqxH4aWF1YAYKaIJohJv16aMdnlc7fsUCuezPHszuAOST8ByEW1nI/NE/4d1S+G8fFGQGLsTARKNN661ECyP7htmmmJRGEFslGf2BqFArXhoLl8nunKsluTTVRRhjeJjFA8YUF5oI/6hsvEp0dx/1QhiirF0tsjWOvV21f+UeQUbgitYSq5U/j3vf9jit8G2eN5Vdz3xnPOy/IfeDvTqp9KSplLZtZ4hV8KaN0BPGoQbPysKF+AGcED9gRAzLjjOuN6sz1ARQZH2YOrbFXY/pWXSL2Gb6TrAuhO57I2WuKn67RsjSnMdBd92thrWYrx6KgwQzvWvsc3j66+7gautW5EtubBz7lsKoSU0KXKJU/AO+fTasXh6k5XG3w+ss4uUKp8cQyRd1xViDbr0w9hvSgG0kMoYk2LssxgmiALrUGTLMT+wlOuoNs2yfteWqXCL4X78jcF+YaL6nDeS3LDTnYKarGtA9BcguzMlo6V3lKIwnSH53Y2zWftEmLqtZa4A/sePWYxh+upC0wFyp+VeTefAlSiJw0g6W6xeSeE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
