travis:
  secure:
    BINSTAR_TOKEN: MBUml68veTW7mmjx2CaRcBsmpz7hpDSXYX3rEoRZint6WLgSh3KGgPv8AyoGb+dNYQHftjOPSVK9yCBSDd5k7bhFS2EaHj5gYGKlQfLdHIhF3sKtsYU0icnTunTmcE+XIrvPzfSPFCpHc0xM1MoPhixBUAcHpI83Bg4OMr9Ssghgt0yzpn4t0zpdzAU9UyH7zjJJ0FhOUBDdceJaMVTfR/VjplY5eOMeFXOV+2cPq+BWxcA7xLyvBo0nD0w29yWc+8unSYrQUI/CDk8Hlitlgi1x/4IeDdMbjrV/bDZj8cucn3PUCISSuMmkqylwp6uzyNMEx6CsVuP+Q3ZI0+PF+EKeFhjCmVmzDsx4CBqZs2Lstb60hhPfmtTTgOapcy71pyVDA896H1YT1UOh76rI80yYSCKg54sT1fopll864qOvyCh9ZczCU2iegmAF23svZ92S8H1Hw+M1z9Sdkdc/MmTjMbjZkWd1PstnDNBwYOCmwr2FlrgyxvjYOj0seEqXx0oF+2BVai8mR5nI4Td10BNGplunmQ/+mEPajaLitmFoLtgK8rqOYxCBTyRkUEzuRAHRi3Mqi0LhM3mpC8sF1Rkuvxu56x9RuemCVm2+aIZJgWdK0GIA3oE6VRtIlbBib9KzhdAhr5huRjJku+I7IgXuz5ru+D3PTRH5IWFF68M=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
